name: PR Docker Build

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/docker-build-shared.yml
    with:
      version: pr-${{ github.event.pull_request.number }}
      build_all: true
      release_as_latest: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}